export type CuratedPublicationLink = {
  doi?: string;
  externalUrl: string;
  source: string;
  checkedAt: "2026-07-20";
  ignoreCitationUrl?: true;
};

// The key is the stable CV candidate fingerprint generated by
// scripts/build-review-seed.ts. Only records without a usable URL or DOI in the
// CV need an entry here. Prefer DOI and publisher/institutional records; use an
// official project page for forthcoming work that does not have a landing page.
export const curatedPublicationLinks: Record<string, CuratedPublicationLink> = {
  fd2966657852b8386d3922b772a2925e4fdb0f7429ae60674f3d351122b5037e: {
    externalUrl:
      "https://www.iseas.edu.sg/media/event-highlights/symposium-on-the-2024-indonesian-elections-and-the-future-of-indonesian-politics/",
    source: "ISEAS project/symposium page",
    checkedAt: "2026-07-20",
  },
  "8c5b06208f55f3268b3965c24364abe17f3492a13e41b351e8658f1eb772caa3": {
    doi: "10.1355/9789815306682",
    externalUrl: "https://doi.org/10.1355/9789815306682",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  f66a2a4dec6e2b346781b6ad4870b7e057eea69a8ff8e2ad9a72f810734c6767: {
    doi: "10.1355/9789815104103",
    externalUrl: "https://doi.org/10.1355/9789815104103",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "0fef24315f97f6745ff40a2923029ec737c707854494670fda8741e22f88d61d": {
    doi: "10.1355/9789815104004",
    externalUrl: "https://doi.org/10.1355/9789815104004",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "896144badd5b73dcdeb52ddaeeb838b63846660e38ace0de027dfee9a09bfce0": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53915",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "070eb96f4a875430279cf81e0654ba461a54a984a9e8f71d683af98710846012": {
    doi: "10.1007/978-981-13-6779-3",
    externalUrl: "https://doi.org/10.1007/978-981-13-6779-3",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "95e7f3d16b4eae1906ba686874c665af3279a997ef041f7288c161e32649159c": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54388",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "3e99a3dc231eed4d3461db270c665d4385eefd1eff8978f6807fa9d0f320cd8c": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53917",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  bd8536bf765a672e6ec6666499a767e64c511c8a1a53ef5b98584d29aa84081a: {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53913",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "043b2c132f53f7e7a7084d9da2712d72054f041191a46cefe14e659797ee7d28": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54387",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "6a7f7e7d62b44d8ebd71e37e9062ca3ad59179dfe535e83e11df02d2b495c8bf": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54391",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "55d80a234e2f9031f88fb86fab43f53b22ee4a87c26f38cc4539142229504475": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54389",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "6092abf4842071364320f8268767e590e426af01b5cb63b37eae44b7669a327f": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54392",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "9f4f68b36f8f42e49f60496523ebc5e9eaa665fed33e35ebaee6baeef4050e34": {
    doi: "10.1355/9789815306651-011",
    externalUrl: "https://doi.org/10.1355/9789815306651-011",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "447b3bda60cc5427062f203d796927e077cc078230b4a5596821279ab40b8a8e": {
    doi: "10.1177/18681034251337763",
    externalUrl: "https://doi.org/10.1177/18681034251337763",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "0dceb9dd01ad230d1c97a0f5b1f03cc0dba19907dc27ad0ce930bd8162da84a0": {
    doi: "10.1355/cs47-2b",
    externalUrl: "https://doi.org/10.1355/cs47-2b",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "60b67a1488b64c145cff0a281c73a27e0d69b23bd1713240a84403f901c4350e": {
    doi: "10.1177/20563051221122792",
    externalUrl: "https://doi.org/10.1177/20563051221122792",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "9d741b3622ca9742e20f753eb77f24c0622d2e55f7d2878adf3066ce9196d872": {
    doi: "10.1355/cs44-1h",
    externalUrl: "https://doi.org/10.1355/cs44-1h",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "9800ca0132a0ac7a5a35cdc3a2567647ba80313c614d0139b944abaf8da2b48f": {
    doi: "10.1080/10357823.2022.2137002",
    externalUrl: "https://doi.org/10.1080/10357823.2022.2137002",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  fa3e1aea373918bcb7d192aa969810665cd8404b6a1a029336b6ffe412208858: {
    doi: "10.1017/S0043887121000216",
    externalUrl: "https://doi.org/10.1017/S0043887121000216",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "7b567ba0ef561375ea5f4721f8e6604777f3cadc8d8af2faf7d27629a15e4643": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/68184",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  be7505ecc53260c55dec324c6fdead7d369ccc5f19367220b1890eb614497e5e: {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/68200",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  d69d9381b4dca54f517bf266d19a80bb7c191353a483c900060aabfb6f715346: {
    doi: "10.1355/cs42-1c",
    externalUrl: "https://doi.org/10.1355/cs42-1c",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  b68530092cdb14aaaff7235fd324f05b6ce2e262522aeef4f92489a7e985797a: {
    doi: "10.47651/MRF.V13I2.23",
    externalUrl: "https://doi.org/10.47651/MRF.V13I2.23",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  c03f2451722cf7ab4b1e82b282e169d0756259fe5f1f28d008010d25fe6b83b8: {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54343",
    source: "UIN Jakarta institutional repository (the DOI printed in the CV currently returns 404)",
    checkedAt: "2026-07-20",
    ignoreCitationUrl: true,
  },
  "8e33127db71c9638b98c163928dfc2203443ab7721f1b4a84087b1f978dc2df9": {
    externalUrl: "https://ikaluinjkt.com/figure/burhanuddin-muhtadi/",
    source: "UIN Jakarta alumni publication profile",
    checkedAt: "2026-07-20",
  },
  "1ff8120f1acfb42037826b5d56d7e63f4058df7e92c213d35bc6e3cd25c48a5c": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53688",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  b0b275f7e6347e5529eb21cedf342edd19d6072e8431f531d8cc06fa02c8ab8b: {
    externalUrl:
      "https://www.researchgate.net/publication/383182028_When_is_Staying_Home_Partisan_Policy_Conflict_and_Precaution-Taking_during_a_Pandemic",
    source: "ResearchGate record audited 19 July 2026",
    checkedAt: "2026-07-20",
    ignoreCitationUrl: true,
  },
  "04c29014c7963eafda4791e1220c0e47fadbe53b8231fd0231859287b8446673": {
    externalUrl:
      "https://www.iseas.edu.sg/media/event-highlights/symposium-on-the-2024-indonesian-elections-and-the-future-of-indonesian-politics/",
    source: "ISEAS project/symposium page",
    checkedAt: "2026-07-20",
  },
  "95e6facc3dc0e3c6cf791df1222e859ed3b03fbdeae8c74a3b77641a5884e742": {
    externalUrl:
      "https://www.universiteitleiden.nl/en/news/2024/02/call-for-papers-indonesia-2014-2024",
    source: "Leiden University edited-volume project page",
    checkedAt: "2026-07-20",
  },
  db75933b0d77fe9257d200a702964234f562809e1419feaf436048dc8eca6c51: {
    externalUrl:
      "https://www.iseas.edu.sg/media/event-highlights/symposium-on-the-2024-indonesian-elections-and-the-future-of-indonesian-politics/",
    source: "ISEAS project/symposium page",
    checkedAt: "2026-07-20",
  },
  "550201da53e92ecad9459753e553350c09eefd50080472cad862c634902fa125": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/68196",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  a5c149d8db5068b4e506b4ceea4ca02ca8df628a5559a1e112d5a1d36ccca190: {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/68193",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "5467ed9baad80c6b2ecb754ee6509263a75809acc92505edfde67f302baff165": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/68198",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "573ad0010a81f1dd34f42fa136c6691919fdbb02fcab308d9a3984d252115a05": {
    doi: "10.1355/9789814881524-013",
    externalUrl: "https://doi.org/10.1355/9789814881524-013",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "1b79f4b206ebd264587e2ee58bcd16680e6b5004ff99cfcc6bde917c25259ab7": {
    doi: "10.4324/9781003010920-2",
    externalUrl: "https://doi.org/10.4324/9781003010920-2",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "9bc5134ce326f5285e4cc83780a1437676bb8e01567b641f2616933301e0bb77": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53912",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "3ef9b5f9db0f1af9a116589a8b7a37f1239160f03de6b4923ef969e2882707f7": {
    doi: "10.1355/9789814843478-013",
    externalUrl: "https://doi.org/10.1355/9789814843478-013",
    source: "Crossref DOI metadata",
    checkedAt: "2026-07-20",
  },
  "1e23497ddc489c4003e1d9127795489a8d609a12d3fa36ad9ed3dab77a2bf4fc": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53914",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "41ea62510031d213a40e2c11154a4a294a408a3e202491b050f4165f2a65d2fb": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/53691",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "1838eec7b01f91c2d1b1d2f23b6214833ead880ab10f3f747335881582f1dbcc": {
    externalUrl: "https://indef.or.id/publikasi/tantangan-kabinet-kerja-memenuhi-ekspektasi/",
    source: "INDEF publication page",
    checkedAt: "2026-07-20",
  },
  "542ecc60c4e8b7dc12142c56599b8dfb4978dde098a3de2d3b96139e63c65ff2": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54399",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "9ac9cf87b31518aa1f4208e432980616d6fad6aa894c3cbe28dfc3bc06abbfb9": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54394",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "43a7ea9361f160e6ea274ba7227861da9a2a2a89296621b3c1a7149ce42b4d1b": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54400",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
  "63a133c7167ec25f6d0fcf4a2309a9104070c2ab29b3b7e44213e5b48ebd86b1": {
    externalUrl: "https://www.brookings.edu/articles/politicizing-inequality-in-indonesian-elections/",
    source: "Brookings canonical article page",
    checkedAt: "2026-07-20",
    ignoreCitationUrl: true,
  },
  "74af43e08c23f4a4ec34c4524ef58618ff18e7f58709719f4341025aa1cfd851": {
    externalUrl: "https://repository.uinjkt.ac.id/dspace/handle/123456789/54398",
    source: "UIN Jakarta institutional repository",
    checkedAt: "2026-07-20",
  },
};
